### ISSUE TITLE
Verweis auf anderen UseCase in Ablaufvariante wird nicht angezeigt (siehe Comments)

### ISSUE THREAD

**Issue by monsterspace** [Fettstorch/OTH_SWP_SS15#111]
![weitermituc-1](https://cloud.githubusercontent.com/assets/7596539/8143728/0ec1b562-11bb-11e5-8879-eddae6aba9fe.png)
![weitermituc-1_dokument](https://cloud.githubusercontent.com/assets/7596539/8143729/145057cc-11bb-11e5-92b1-df1b6cc833b8.png)

**Comment by monsterspace** [comment]
Es wird hier schön angezeigt, dass die Ablaufvariante und somit der ganze UseCase dort aufhört (da es ja eig bei UC-1 weitergeht)
Es steht aber nirgends in den Properties, dass es dann eig mit UC-1 weitergehen würde

**Comment by Coder-Luke** [comment]
@Ratatoeskr @DasAddition

**Comment by Ratatoeskr** [comment]
"Weiter mit: XYZ" Wird nun in der Description angezeigt
