### ISSUE TITLE
Doppelte UseCase-Bezeichnungen werden ignoriert

### ISSUE THREAD

**Issue by monsterspace** [Fettstorch/OTH_SWP_SS15#112]
Laut Anforderung soll bei doppelter UseCase-Bezeichnung (UC-x doppelt oder mehrfach) eine Warnung beim Einlesen ausgegeben werden und nur der erste davon interpretiert und angezeigt werden

![doppelteusecasebezeichnung](https://cloud.githubusercontent.com/assets/7596539/8143807/477abfbc-11bf-11e5-919f-3ee4bdc4bb1f.png)

**Comment by Ratatoeskr** [comment]
Der Name darf ab nun auch nicht doppelt vorkommen. Hat sich gleich angeboten, dass ich das da auch gleich so implementier
