### ISSUE TITLE
Deutsch/Englisch gemischt in Fehlertext bei dem Versuch eine korrupte Datei zu öffnen

### ISSUE THREAD

**Issue by monsterspace** [Fettstorch/OTH_SWP_SS15#113]
![deutschenglisch_messagebox](https://cloud.githubusercontent.com/assets/7596539/8143850/5a733e9e-11c1-11e5-80c0-4d5e7c20da94.png)

**Comment by Coder-Luke** [comment]
@Ratatoeskr @DasAddition

**Comment by Parsen07** [comment]
@Ratatoeskr 
@SPoelloth 

--> exceptions catchen und weiterwerfen mit eigener message, die dann dem user angezeigt wird (englisch)
