### ISSUE TITLE
UseCaseGraph und View: Anzahl Schleifendurchläufe parametrierbar machen

### ISSUE THREAD

**Issue by SebMertz** [Fettstorch/OTH_SWP_SS15#125]
@Parsen07 Es muss noch ein Attribut zu jedem UseCase hinzugefügt werden, mit dem die Anzahl an Schleifendurchläufen einstellbar ist. Die Vorgehensweise sollte so wie für die Anzahl Varianten die traversiert werden sein. Dies sollte dann auch über die View je UseCase einstellbar sein. Änderungen im ScenarioMatrixCreator macht dann anschließend @SebMertz .

**Comment by Parsen07** [comment]
TO DO: attribut im scenario creator auslesen
