### ISSUE TITLE
Falsche Bezeichnung einer Ablaufvariante führt zu unklarem Programmverhalten (siehe Comments)

### ISSUE THREAD

**Issue by monsterspace** [Fettstorch/OTH_SWP_SS15#131]
anstatt 2a habe ich A2 geschrieben, das ist das resultat und die source:
![2015-06-23 23_08_45-usecase analyser](https://cloud.githubusercontent.com/assets/7596539/8317338/f82c9fac-19fc-11e5-80ac-9a0f6422e1ce.png)
![2015-06-23 23_08_16-usecase_test1 docx - microsoft word](https://cloud.githubusercontent.com/assets/7596539/8317339/f8e05e0c-19fc-11e5-98ec-886f2376dd94.png)

**Comment by Ratatoeskr** [comment]
besteht das Problem immer noch? Wenn nicht würd ich gerne closen :)
