### ISSUE TITLE
Anforderungsdokument/Lastenheft aktualisieren und Reviewen

### ISSUE THREAD

**Issue by schneider-mathias** [Fettstorch/OTH_SWP_SS15#15]
Alle Änderungen rund ums Lastenheft...

**Comment by schneider-mathias** [comment]
Aktualisierung Lastenheft

Nummerierung innerhalb der UCs war nicht korrekt.

```
work_branch_general 
```

commit 710ceaae434ab7aaa868bc230e7558422dbc75e6 1 parent cc51082
@Fettstorch Fettstorch authored a minute ago

**Comment by r0oto0r** [comment]
Ersten Review schließe ich ab bis 22.04
