### ISSUE TITLE
Prototyp "Graph zeichnen" erstellen

### ISSUE THREAD

**Issue by r0oto0r** [Fettstorch/OTH_SWP_SS15#18]

**Comment by schneider-mathias** [comment]
Nette Quelle mit verschiedenen Algorithmen: http://graphsharp.codeplex.com/

**Comment by r0oto0r** [comment]
Verantwortlich: Patrick + Mathias

**Comment by schneider-mathias** [comment]
Weitere Algorithmen: http://www.graphviz.org/Documentation/TSE93.pdf

**Comment by schneider-mathias** [comment]
Arrow: http://www.codeproject.com/Articles/17417/Draw-Straight-and-Curved-Arrows
