### ISSUE TITLE
Git Account RL Name

### ISSUE THREAD

**Issue by r0oto0r** [Fettstorch/OTH_SWP_SS15#20]
Um euch etwas besser bestimmten Issues zuteilen zu können, wäre es vll sinnvoll, dass ihr hier im Comment mal eben euren Vornamen posted, dann weiß ich wer, wer ist.

**Comment by Coder-Luke** [comment]
Patrick

**Comment by schneider-mathias** [comment]
https://github.com/Fettstorch/OTH_SWP_SS15/blob/work_branch_general/Basisverzeichnis/trunk/06_Skripte/SetEnv_User.bat

**Comment by r0oto0r** [comment]
Alles klar, vielen dank!
