### ISSUE TITLE
Codierungsrichtlinien festlegen

### ISSUE THREAD

**Issue by schneider-mathias** [Fettstorch/OTH_SWP_SS15#3]
Must-have:
-Einigung auf Coderichtlinien (und falls nötig Tool, z.B. Resharper)
-Wiki-Eintrag zum nachlesen

**Comment by schneider-mathias** [comment]
Allgemeine Codierungsrichtlinien:
https://msdn.microsoft.com/de-de/library/ff926074.aspx

Ausnahmen: 
 -Verwendung von var.

Sonstige Vereinbarungen:
 -Public Methoden groß geschrieben
 -Private Methoden klein
 -Member starten mit Prefix 'm'
 -Interface Klassen Prefix 'I'
 -keine ungarische Notation

Bitte erweitern!

**Comment by r0oto0r** [comment]
Struktur von Klassen:

public static Members
private static Members
public Members
private Members
Getter/Setter (Felder)
Konstruktoren
Destruktor
public Methoden
private Methoden
