### ISSUE TITLE
Implementierung Tests Framework

### ISSUE THREAD

**Issue by SebMertz** [Fettstorch/OTH_SWP_SS15#35]

**Comment by schneider-mathias** [comment]
Bitte Überprüfen 
AddNodeExceptionTest TestCase(0) liefert keine Exception und geht damit schief!
-> geht nicht in Schleife -> Lösung for (int i = 0; i <= count; i++)

-> damit geht der Test dann noch schief, liegt dann aber an der fehlenden defensiven Implementierung in AddNode() -> Abprüfung auf null
@SebMertz @Ratatoeskr

**Comment by SebMertz** [comment]
Das Problem mit der Prüfung auf null im AddNodeExceptionTest TestCase(0) ist jetzt mit dem neuen Stand angepasst. Der TestCase heißt jetzt AddNull.
@Fettstorch

**Comment by SebMertz** [comment]
Damit laufen jetzt alle Tests ohne Fehler durch, wird geschlossen
