### ISSUE TITLE
Framework Klassendiagramm anpassen

### ISSUE THREAD

**Issue by r0oto0r** [Fettstorch/OTH_SWP_SS15#38]
- Statische Methoden bei Graph
- Fehlende Parameter ergänzen
- RemoveEdge -> params IEdge[].....
- RemoveNode -> params INode[].....
- GetEdges (Graph) mit zwei Nodes als Parameter

**Comment by SebMertz** [comment]
Sollte damit erledigt sein, wird damit geschlossen @Parsen07

**Comment by SebMertz** [comment]
Anpassungen für ScenarioMatrixCreator
