### ISSUE TITLE
Code-Review Framework: [Attribute] Setter prüft null & nullorwhitespace

### ISSUE THREAD

**Issue by r0oto0r** [Fettstorch/OTH_SWP_SS15#44]
- Warum genau prüft der setter null zweimal?
- Exception würde mir als Benutzer nicht wirklich helfen -> evtl Standard Exception verwenden e.g. ArgumentNullException

**Comment by Ratatoeskr** [comment]
Versteh das Review nicht? O.o 
Passt iwie nicht zu dem code :(
