### ISSUE TITLE
Code-Review Framework: [Graph] Keine Kommentare?

### ISSUE THREAD

**Issue by r0oto0r** [Fettstorch/OTH_SWP_SS15#48]
- Alle Klassen des Frameworks haben eher zu viele Kommentare, außer Graph, dort gibt es faktisch nur Inline-Kommentare -> y?

**Comment by Parsen07** [comment]
hatte gedacht, da die kommentare die gleichen wären wie bei der schnittstelle sind sie überflüssig, da man in der regel eh mit dem interface arbeitet. 
aber kann die auch noch rein copy pasten

**Comment by r0oto0r** [comment]
Mir geht es da mehr um Konsistenz. Da in den anderen Klassen Kommentare sind sollten hier auch welche sein oder die Kommentare in den anderen Klassen entfernt werden.
