### ISSUE TITLE
Code-Review Framework: [Graph] Unschlüssige Kommentare

### ISSUE THREAD

**Issue by r0oto0r** [Fettstorch/OTH_SWP_SS15#49]
- Nennt mich dumm, aber ich raffe folgende Kommentare nicht:
- 36ff, 76ff, 96, 102

**Comment by Parsen07** [comment]
36ff, 76ff : die ersten beiden waren obsolet, weil die auf einen parameter bezogen war, der jetzt weg ist
--> entfernt
96: typo verbessert
102: angepasst, vlt jetzt verständlicher
