### ISSUE TITLE
Code-Review Framework: [Graph] Unklare Exceptions

### ISSUE THREAD

**Issue by r0oto0r** [Fettstorch/OTH_SWP_SS15#50]
- Warum wirft AddNode, RemoveNode und RemoveEdge eine Exception, wenn der Node nicht im Graph ist?

**Comment by Parsen07** [comment]
- add node wirft, wenn die node schon vorhanden ist
- remove node wirft wenn des remove failt (i.d.R. wenn die node nicht vorhanden ist) --> man sollte nix removen was nicht drinne ist
- remove edge analog zu remove node

**Comment by Parsen07** [comment]
exceptions in der graph klasse angepasst. --> tests laufen (s. Checkin Kommentar)
