### ISSUE TITLE
Code-Review Framework: [Graph] Sprechende Variablen- und Parameternamen

### ISSUE THREAD

**Issue by r0oto0r** [Fettstorch/OTH_SWP_SS15#51]
- Für die Lesbarkeit, sollten die Variablen bzw Parameter sprechendere Namen haben
- siehe 61ff n1 besser node1 oder leftNode, rightNode (e.g.)
- siehe 100, 107 g2 -> graphToAdd2 o.Ä.
- Bitte nochmal drüber schaun

**Comment by Parsen07** [comment]
- angepasst, sollte auch im interface angepasst werden
