### ISSUE TITLE
Code-Review Framework: [Graph] Auslagern gleicher Funktionalität

### ISSUE THREAD

**Issue by r0oto0r** [Fettstorch/OTH_SWP_SS15#52]
- Um die Lesbarkeit / Wartbarkeit sollten ähnliche, gleiche Funktionalitäten in einer privaten Methode ausgelagert werden.
- siehe 63ff -> auslagern in eine Methode addIfNotExist (e.g.)
- nennt mich ruhig kleinlich ;-)

**Comment by Parsen07** [comment]
- angepasst
