### ISSUE TITLE
Bug: Zuweisung eines selektierten GraphElements wird eine Exception geworfen

### ISSUE THREAD

**Issue by Coder-Luke** [Fettstorch/OTH_SWP_SS15#58]
Es wird eine Exception geworfen sobald ein GraphElement zugewisenen wird das kein Graph ist (z.B. Node oder Edge)
![zwischenablage01](https://cloud.githubusercontent.com/assets/11528765/7617008/d3115f92-f9a8-11e4-9498-bb223ad77abf.jpg)

**Comment by schneider-mathias** [comment]
Aus dem IGraph scenerioGraph =value as IGraph, sollte
IGraphElement scenarioGraph = value as IGraphElement;
gemacht werden -> dann aber vllt auch gleich den Namen der Klasse ändern, passt dann ja nicht mehr ganz (oder du hattest dir überlegt verschiedene Klassen dafür anzulegen, dann müsste natürlich mehr gemacht werden - glaub allerdings nicht, dass du dir das so gedacht hattest)

**Comment by schneider-mathias** [comment]
Gefixt wie vorgeschlagen.
