### ISSUE TITLE
ScrollViewer im GraphVisualiser funktioniert nicht

### ISSUE THREAD

**Issue by schneider-mathias** [Fettstorch/OTH_SWP_SS15#60]
Beschreibung:
Scrollbar bleibt unaktiv, auch wenn der UseCase Graph über die Zeichenfläche hinausragt.

Reproduzierbarkeit:
Großer UseCase Graph als Input.

Seit: b6e64fd5f19fb6daa28119e6e324826a7ecfce9f

**Comment by Coder-Luke** [comment]
solte nun passen
