### ISSUE TITLE
Systemarchitektur Framework & Tool: Anfertigen der Schnittstellendefinitionen

### ISSUE THREAD

**Issue by r0oto0r** [Fettstorch/OTH_SWP_SS15#63]
- Für das Dokument Systementwurf_Framework_Tool muss eine Übersicht aller Schnittstellen angefertigt werden
- Jedes Team erstellt eine Schnittstellendefinition all seiner öffentlichen (nicht internen) Schnittstellen
- Diese in den Ordner Entwurf speichern: Schnittstellendefinition_SCHNITTSTELLENNAME
- Milestone beachten!!!!

**Comment by r0oto0r** [comment]
@Fettstorch
@Parsen07 
@monsterspace 
@Coder-Luke 
@SebMertz 
@DasAddition
@SPoelloth 
@Ratatoeskr

**Comment by r0oto0r** [comment]
@Fettstorch Wäre es möglich, dass du mal schaust, was mit mit DoxyGen (o.Ä.) reißen können? (Das setzt aber vorraus, das der Rest seine Schnittstellen sauber kommentiert hat)

**Comment by schneider-mathias** [comment]
Ja ich habe Doxygen mal darüber laufen lassen, sieht recht schön aus, allerdings muss ich die Filterung noch besser hinbekommen (z.B. werden die Tests  mit in die Doku reingenommen)... gebt mir da vllt bis Mittwoch bevor ihr händisch damit anfangt, da etwas zu schreiben bzw. konzentriert euch darauf die Kommentare wirklich sauber zu haben. Einen Ersten Entwurf von Doxygen mittels LaTex erstellten Pdf stelle ich mal in Facebook online.

EDIT: Kommando zurück, schaut bitte, dass ihr das was in der Pdf drinsteht vllt in die Vorlage übernehmen könnt. Zeitkritische Dokumente will ich nicht toolbasiert abgeben.

EDIT,EDIT: Hatte zunächst gedacht das wäre den Mittwoch - bis nächsten Mittwoch sollte das mit Doxygen passen.

**Comment by r0oto0r** [comment]
Besprechen wir am 20.05.15
