### ISSUE TITLE
WordImporter gibt Dokument nicht wieder frei

### ISSUE THREAD

**Issue by schneider-mathias** [Fettstorch/OTH_SWP_SS15#74]
Beschreibung: Nachdem Word Dateien importiert wurden, können auf diese, während der UseCaseAnalyser noch läuft, nicht schreibend zugeriffen werden (z.B. von Word). 

Vorschlag:
-> doc.Close()? oder using (...){} verwenden

Reproduzierbarkeit: Importieren eines Word Dokuments und versuch nach dem Import solange der UseCaseAnalyser noch läuft zu Öffnen -> schreibgeschützt.

Seit: immer schon (eb9f64ca842b9024ea81559b3163879b1f68edc3)

**Comment by Coder-Luke** [comment]
Sollte nun behoben sein. Hab dafür im Code ergänzt:
doc.Close();
doc.Dispose();
