### ISSUE TITLE
WordImporter ArgumentOutOfRangeException

### ISSUE THREAD

**Issue by schneider-mathias** [Fettstorch/OTH_SWP_SS15#78]
Beschreibung: Weder UseCaseDummies.docx noch 20150414_Anforderungen.docx lassen sich einlesen. 
![wordimporterargnullexception](https://cloud.githubusercontent.com/assets/7561726/7796397/4d6e1d0e-02df-11e5-9fd0-dab0ce4490c4.png)

(Abgesehen davon, bin ich mir unsicher, ob der User sich überhaupt für die Art der Exception interessiert, vielleicht sollte diese nicht einfach geworfen werden und dann 1:1 in der MessageBox stehen)

Erste Debugging Ergebnisse zeigen, dass in diesem Riesen-If des WordImporters Zeile 173ff die Exception fliegt.

Reproduzierbarkeit: UseCaseDummies.docx importieren

Seit: c3827bdba886c58329cfc5240496ca45072af9f1

**Comment by Parsen07** [comment]
mit der exception in der message box hast du schon recht aber was würdest du darstellen? 
was würdest du in der message box ausgeben ?

**Comment by schneider-mathias** [comment]
Wäre für "Fehler beim Einlesen" - Für nähere Informationen bitte in das LogFile schauen. (Die Exception mit Text sollte da dann reingeloggt werden)

**Comment by Ratatoeskr** [comment]
find die exceptionmessagebox eigl nicht schlecht. Es sollten ja im Idealfall eh keine exceptions geworfen werden, somit ist die MessageBox nur für uns wichtig. Für den user gibs ja dann den Report

**Comment by schneider-mathias** [comment]
"... somit ist die MessageBox nur für uns wichtig" genau aus diesem Grund sollten wir den genauen Exception-Text doch nicht dem User zeigen? Als Anwender, der keine Ahnung von Code hat, würde mich ein solcher Fehler (auch wenn er nicht vorkommen sollte) nur verwirren.
