### ISSUE TITLE
Graph.Visualiser - Kanten ordnen sich bei Reload des UseCases neu an 

### ISSUE THREAD

**Issue by schneider-mathias** [Fettstorch/OTH_SWP_SS15#82]
Vorher:
![edgesreload_before](https://cloud.githubusercontent.com/assets/7561726/7798645/b0d4d5dc-02fc-11e5-8176-26d106294bcd.png)

Nachher:
![edgesreload_after](https://cloud.githubusercontent.com/assets/7561726/7798649/bcd916d6-02fc-11e5-8400-110204974635.png)

**Comment by Coder-Luke** [comment]
Sollte bereits behoben sein, muss noch überprüft werden

**Comment by schneider-mathias** [comment]
Bitte noch den Check-In verlinken, dann kann geclosed werden :)
