### ISSUE TITLE
WordImporter - the content of 'Spezielle Anforderungen:' could not be interpreted

### ISSUE THREAD

**Issue by schneider-mathias** [Fettstorch/OTH_SWP_SS15#88]
Beschreibung: 
Beim Import der Datei trunk\04_Test\TestFiles\UseCase_RingClosure_1.docx wird der UC-2 nicht eingelesen - Report zeigt "the content of 'Spezielle Anforderungen:' could not be interpreted"
--> In der .docx sehe ich keinen Format-Fehler, bitte Untersuchen

Reproduzierbarkeit: Import der Datei trunk\04_Test\TestFiles\UseCase_RingClosure_1.docx

Seit: cefc5e399bcd5adf94e6ed8fe0dfda8c3e50e102 eher noch früher

**Comment by Ratatoeskr** [comment]
Der Fehler entsteht dadurch, dass die Tabelle eine Zeile zu viel hat. Werde morgen den WordImporter überarbeiten, dass solche Fehler nicht entstehen, bzw. die Zeilennummer nicht mehr fest sein muss und wir insgesamt eine höhere Fehlertoleranz bei dem Importieren haben
