### ISSUE TITLE
Tool gibt keine Rückmeldung, dass leeres UseCase-Dokument eingelesen werden soll

### ISSUE THREAD

**Issue by monsterspace** [Fettstorch/OTH_SWP_SS15#94]
UC-1 (UseCase-Dokument Importieren)... Ablaufvariante 4c (hier ist vermerkt, dass Tool meldet, wenn das WORD-File leer ist)
Entweder Funktionalität hinzufügen oder Anforderungen bearbeiten

**Comment by Ratatoeskr** [comment]
Es gibt eigl schon ne Warnung, aber die wird ja nicht angezeigt. Hab die Warning jetzt mal zum Error gemacht. Schöner würde ichs eigl finden, wenn der Report auch bei warnings geöffnet wird
