### ISSUE TITLE
Fehler in der Einfärbung verschiedener Szenarien (Pfeile nicht rot)

### ISSUE THREAD

**Issue by monsterspace** [Fettstorch/OTH_SWP_SS15#95]
Unter Test - Testfiles - UseCase_Correct_Abstract.docx
ist das Dokument mit dem der Fehler entdeckt wurde 
![issue-szenario-farbung](https://cloud.githubusercontent.com/assets/7596539/7934021/10ed8770-0924-11e5-9a82-5f4ef80aa88c.png)

**Comment by schneider-mathias** [comment]
Nach kurzem Logging scheint es so, als wären diese Kanten nicht im IGraph Scenerio Object enthalten @SebMertz magst du vllt nochmal drauf schauen?
