### ISSUE TITLE
Fehler in der Szenarioerstellung (Details in den Comments)

### ISSUE THREAD

**Issue by monsterspace** [Fettstorch/OTH_SWP_SS15#98]
Geht vom letzten Knoten des Normalablaufs eine Ablaufvariante ab (siehe Beispiel hier: 2a1),
so wird diese nicht vom Szenariocreator erstellt (siehe Liste auf Bild rechts).
![szenario ausgehen vom letzten schritt des normalablaufs](https://cloud.githubusercontent.com/assets/7596539/7954768/c75c763e-09d2-11e5-9b71-2cfd929e3fa0.jpg)

**Comment by monsterspace** [comment]
und ja, ich habe darüber nachgedacht ob sowas überhaupt auftreten kann. Meiner Meinung nach kann es das, da der letzte Schritt im Normalablauf ja noch nicht der Ende-Knoten ist

**Comment by schneider-mathias** [comment]
Kann geclosed werden oder?
